from .mathtext import frac_part as F, sub, sup

FORMULAS = [
    {
        "name": "First Order Rate Constant",
        "tag": "Kinetics",
        "formula": ["k = ", F("2.303", "t"), f"  log(R{sub(0)}/R)"],
        "meaning": "Gives the rate constant of a first order reaction from concentrations at two times.",
        "variables": "k = rate constant, t = time elapsed, R0 = initial concentration, R = concentration at time t",
        "units": f"k -> time{sup(-1)} (e.g. s{sup(-1)}, min{sup(-1)})",
        "conditions": "Valid only for reactions that are first order overall.",
        "mistakes": "Forgetting the 2.303 factor when converting ln to log10; mixing up R0 and R inside the log.",
        "trick": "log(R0/R) is always positive since R0 > R for a forward reaction — a negative result signals swapped values.",
        "memory": "\"2.303 over t, log the ratio\" — say it as one phrase.",
        "example": "R0 = 0.8 M, R = 0.4 M, t = 20 min -> k = (2.303/20) log(2) = 0.0347 min-1",
    },
    {
        "name": "First Order Half-Life",
        "tag": "Kinetics",
        "formula": ["t\u00bd = ", F("0.693", "k")],
        "meaning": "Time required for concentration to fall to half its initial value; constant for first order reactions.",
        "variables": "t1/2 = half-life, k = rate constant",
        "units": "t1/2 -> same time unit used for k-1",
        "conditions": "Independent of initial concentration — a hallmark of first order kinetics.",
        "mistakes": "Using this formula for zero or second order reactions, where half-life depends on concentration.",
        "trick": "0.693 is just ln(2) — recall ln(2) \u2248 0.693 to rebuild the formula instantly.",
        "memory": "\"Half-life never lies\" for first order — always the same value.",
        "example": "k = 0.0347 min-1 -> t1/2 = 0.693/0.0347 \u2248 20 min",
    },
    {
        "name": "Zero Order Rate Law",
        "tag": "Kinetics",
        "formula": ["k = ", F(f"R{sub(0)} \u2212 R", "t")],
        "meaning": "Rate constant for a zero order reaction, where rate is independent of concentration.",
        "variables": "R0 = initial concentration, R = concentration at time t, t = time",
        "units": f"k -> mol L{sup(-1)} time{sup(-1)}",
        "conditions": "Applies when reaction rate does not change with reactant concentration (e.g. surface-catalysed reactions).",
        "mistakes": "Applying the first-order log formula by mistake; forgetting that k here carries concentration units.",
        "trick": "Zero order graphs are a straight line of [R] vs t — spot it visually before calculating.",
        "memory": "\"Zero order, straight decline.\"",
        "example": "R0 = 1.0 M, R = 0.8 M, t = 20 min -> k = (1.0-0.8)/20 = 0.01 mol L-1 min-1",
    },
    {
        "name": "Second Order Rate Law",
        "tag": "Kinetics",
        "formula": [F("1", "R"), " = ", F("1", f"R{sub(0)}"), " + kt"],
        "meaning": "Relates concentration to time for a second order reaction.",
        "variables": "R0 = initial concentration, R = concentration at time t, k = rate constant, t = time",
        "units": f"k -> L mol{sup(-1)} time{sup(-1)}",
        "conditions": "Applies when rate depends on the square of one reactant's concentration (or product of two reactants).",
        "mistakes": "Forgetting to invert both concentrations before subtracting; unit mismatch with first-order k.",
        "trick": "A straight line of 1/[R] vs t confirms second order behaviour.",
        "memory": "\"Flip it, then add kt.\"",
        "example": "R0 = 1 M, k = 0.02 L mol-1 min-1, t = 20 min -> 1/R = 1 + 0.4 = 1.4 -> R \u2248 0.714 M",
    },
    {
        "name": "Arrhenius Equation",
        "tag": "Kinetics",
        "formula": ["k = A e", "^(\u2212Ea/RT)"],
        "meaning": "Describes how rate constant depends on temperature and activation energy.",
        "variables": "k = rate constant, A = pre-exponential factor, Ea = activation energy, R = gas constant, T = temperature (K)",
        "units": "Ea -> J/mol (use R = 8.314 J/mol/K) or kJ/mol (use R = 0.008314 kJ/mol/K)",
        "conditions": "Temperature must be in Kelvin; assumes Ea is constant over the range considered.",
        "mistakes": "Mixing kJ and J units for Ea and R; using \u00b0C instead of Kelvin.",
        "trick": f"For two temperatures, skip solving for A — use ln(k{sub(2)}/k{sub(1)}) = \u2212Ea/R (1/T{sub(2)} \u2212 1/T{sub(1)}).",
        "memory": "\"Bigger T, bigger k — always increasing.\"",
        "example": "Ea = 75 kJ/mol, k1 at 300 K, T2 = 310 K -> k2 > k1, computed via the two-point form.",
    },
    {
        "name": "Mole-Mass Relation",
        "tag": "Mole Concept",
        "formula": ["n = ", F("m", "M")],
        "meaning": "Converts a given mass of a substance into number of moles.",
        "variables": "n = number of moles, m = given mass, M = molar mass",
        "units": "n -> mol, m -> g, M -> g/mol",
        "conditions": "M must correspond to the correct chemical formula (watch for hydrates, ions).",
        "mistakes": "Using atomic mass instead of molar mass for compounds; forgetting water of crystallisation in hydrates.",
        "trick": "Sanity check: multiply n x M and confirm it returns the original mass.",
        "memory": "\"Moles = mass over molar mass — m over M.\"",
        "example": "5 g of NaOH (M = 40 g/mol) -> n = 5/40 = 0.125 mol",
    },
]
