"""
CAT Lab — Benchmark Report Stylesheet System.
Creator: Kazi Zillani (CAT Platform).

Separates raw benchmark measurements from presentation formatting.
Supports custom themes, table styles, chart styles, and header/footer branding.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, Optional

from .models import BenchmarkRunResult, BenchmarkStylesheet
from ..storage import get_subpath


class StylesheetManager:
    """Manages visual presentation stylesheets for benchmark reports."""

    def __init__(self, styles_dir: Optional[str] = None):
        self.styles_dir = styles_dir or get_subpath("settings", "stylesheets")
        os.makedirs(self.styles_dir, exist_ok=True)
        self._styles: Dict[str, BenchmarkStylesheet] = {}
        self._load_defaults()

    def _load_defaults(self):
        default_style = BenchmarkStylesheet(
            name="default",
            version="1.0.0",
            layout="compact",
            typography="unicode",
            chart_style="bar_unicode",
            table_style="rounded",
            dark_presentation=True,
            header_branding="🐱 CAT Lab — Benchmark Report",
            footer_notes="Generated by CAT (Coding Agent Terminal)",
        )
        minimal_style = BenchmarkStylesheet(
            name="minimal_ascii",
            version="1.0.0",
            layout="minimal",
            typography="ascii",
            chart_style="bar_ascii",
            table_style="ascii",
            dark_presentation=False,
            header_branding="CAT Benchmark",
            footer_notes="CAT Benchmarking Engine",
        )
        self._styles["default"] = default_style
        self._styles["minimal_ascii"] = minimal_style

    def get(self, name: str = "default") -> BenchmarkStylesheet:
        return self._styles.get(name, self._styles["default"])

    def register(self, sheet: BenchmarkStylesheet) -> None:
        self._styles[sheet.name] = sheet
        dest = os.path.join(self.styles_dir, f"{sheet.name}.json")
        try:
            with open(dest, "w", encoding="utf-8") as f:
                json.dump(sheet.to_dict(), f, indent=2)
        except Exception:
            pass


_GLOBAL_STYLESHEET_MGR: Optional[StylesheetManager] = None


def get_stylesheet_manager() -> StylesheetManager:
    global _GLOBAL_STYLESHEET_MGR
    if _GLOBAL_STYLESHEET_MGR is None:
        _GLOBAL_STYLESHEET_MGR = StylesheetManager()
    return _GLOBAL_STYLESHEET_MGR
